### ISSUE TITLE
Diffuser en CSW - Marche à suivre : Lien ne mène à rien

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#33]
Le lien pour ["diffuser ses données sur data.gouv.fr"](http://help.isogeo.com/admin/fr/features/publish/csw_server.html#marche-%C3%A0-suivre) ne mène à rien

Quand on l'ouvre dans un nouvel onglet, ça ouvre le sommaire du help.

![image](https://user-images.githubusercontent.com/63340073/81829759-89755a80-953b-11ea-96fa-2b4d3c538b8c.png)

**Comment by leodarengosse** [comment]
Mis à jour lors du passage à dcat pour data.gouv
