### ISSUE TITLE
Valoriser - Diffuser un OpenCatalog : Lien mène à une page non trouvée

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#34]
Le lien de [l'exemple du portail de la PPIGE](http://help.isogeo.com/admin/fr/features/publish/share_opencatalog.html#oc_header) mène vers une page qui n'existe plus.

![image](https://user-images.githubusercontent.com/63340073/81830630-9a729b80-953c-11ea-9960-17facc6bf58e.png)

**Comment by leodarengosse** [comment]
Il n'y a plus de lien vers la ppige
