### ISSUE TITLE
Annexes - Diffuser ses donner sur DataGouv.fr : liens ne mènent à rien

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#36]
Les deux hypertextes des mots [prérequis](http://help.isogeo.com/admin/fr/appendices/harvest_datagouv_fr.html#submitCSW) de la partie "Référencement et moissonnage du flux CSW" ne mène à rien.

![image](https://user-images.githubusercontent.com/63340073/81837521-44eebc80-9545-11ea-9a4a-edd891d164c9.png)
![image](https://user-images.githubusercontent.com/63340073/81837583-546e0580-9545-11ea-9eb3-0c6593672697.png)

L'hypertexte du mot [prérequis](http://help.isogeo.com/admin/fr/appendices/harvest_datagouv_fr.html#publish) de la partie "Publier sur data.gouv.fr" ne mène à rien.

![image](https://user-images.githubusercontent.com/63340073/81838567-9481b800-9546-11ea-92c4-354f69fe295a.png)

Quand on ouvre les trois hypertextes dans un nouvel onglet, ça mène vers le sommaire du help.

**Comment by leodarengosse** [comment]
Remplacé par la diffusion DCAT
