### ISSUE TITLE
MàJ de la saisie manuelle d'une emprise géographique

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#45]
## Problème 
Partie sur la [saisie manuelle d'une emprise géographique](https://help.isogeo.com/admin/fr/features/documentation/md_geography.html#saisie-manuelle-dune-emprise-g%C3%A9ographique) obsolète depuis le changement de méthode d'ajout de l'emprise.

**Comment by leodarengosse** [comment]
Je ne vois pas ce qui a changé ou alors la doc a déjà été mise à jour
