### ISSUE TITLE
Capture d'écran de l'onglet ressources et partie sur les services géographiques obsolètes

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#47]
Capture d'écran de l'[onglet ressources](https://help.isogeo.com/admin/fr/features/documentation/md_ressources.html) et partie sur [les services géographiques](https://help.isogeo.com/admin/fr/features/documentation/md_ressources.html#services-cartographiques) obsolètes. La remplacer avec une capture d'écran plus récente.

**Comment by leodarengosse** [comment]
Ticket déjà traité
