### ISSUE TITLE
Typo dans l'administration des mots-clés

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#48]
Dans la partie [Via l'administration](https://help.isogeo.com/admin/fr/features/admin/keywords.html#via-ladministration), dans les fonctionnements détaillés : 

![image](https://user-images.githubusercontent.com/63340073/115404222-6a705580-a1ed-11eb-9256-c4dddf45cf59.png)

de smots-clés --> des mots-clés

**Comment by leodarengosse** [comment]
Ticket déjà traité
