### ISSUE TITLE
màj la page sur la possibilité de développement sur l'API

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#67]
https://help.isogeo.com/admin/fr/features/publish/usages_api.html

Modifications à apporter : 

1. suppression des parties "Lancez vous" et "L'export vers les formats bureautiques"
2. màj la partie "les principes" (elle donne l'impression qu'on peut accéder à l'api gratuitement

**Comment by SimonSAMPERE** [comment]
![image](https://github.com/isogeo/doc-admin/assets/41120579/da5240d5-8a8e-410a-ba1b-8680b0421635)
