### ISSUE TITLE
Ajouter les infos du connector jmap

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#72]

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C je peux la trouver où cette doc ?

**Comment by leodarengosse** [comment]
@SimonSAMPERE https://help.qa.isogeo.com/admin/fr/features/publish/jmap_connector.html

**Comment by SimonSAMPERE** [comment]
* Quelques coquilles dans la rubrique "Dans JMAP Admin"
  * manque un " "
    ![image](https://github.com/isogeo/doc-admin/assets/41120579/da746b94-618d-4b1b-af05-3a98e5bea721)
  * je crois que ça devrait être le point 8 et pas 1
    ![image](https://github.com/isogeo/doc-admin/assets/41120579/e3b81c2b-27cb-40b5-b4c1-6256e8708019)
* Une phrase mal formulée dans "Synchronisation et résultat" (ptet moyen de faire 2 phrases genre "établissement des correspondances" puis "g"n"ration des URL pour les données matchées")
  ![image](https://github.com/isogeo/doc-admin/assets/41120579/5254ab90-1529-44d5-bfb3-6b24e3697f3d)
* pas de capture pour JMAP Pro
  ![image](https://github.com/isogeo/doc-admin/assets/41120579/f903f977-e071-45da-b0b9-e78c70d374e6)
* Quelques coquille dans "Vérification des logs" :
  * "Métaddonées"
    ![image](https://github.com/isogeo/doc-admin/assets/41120579/68643aef-aff4-4be8-98a5-0be2f96dc687)
  * "Mistches"
    ![image](https://github.com/isogeo/doc-admin/assets/41120579/c830bcf7-9279-4600-83f0-fa4dde4d6517)
  * "a était" au lieu de "a été"
    ![image](https://github.com/isogeo/doc-admin/assets/41120579/34200b83-aa87-4b00-881c-962bac8d8640)

**Comment by leodarengosse** [comment]
J'ai rajouté les coquilles que j'ai trouvées dans le commentaire de Simon sinon je pense que tu peux présenter les prérequis exactement comme pour [i2o](https://help.isogeo.com/isogeo2office/fr/requirements.html#isogeo)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C j'ai trouvé une dernière coquille
![image](https://github.com/isogeo/doc-admin/assets/41120579/406fc20a-bbb6-4d4a-b5ee-72b020abff83)
