### ISSUE TITLE
Documentation sur l'export csv

### ISSUE THREAD

**Issue by Erzalt** [isogeo/doc-admin#74]
Ajout de la doc sur [l'export csv](https://github.com/isogeo/doc-admin/blob/master/fr/features/documentation/md_attributes.md#export-des-attributs-en-csv). Il faut sûrement effectuer des captures d'écrans pour que cela soit plus clair.

**Comment by leodarengosse** [comment]
Petite erreur "Champs" au singulier --> "champ"  , l'erreur est faite plusieurs fois

**Comment by Erzalt** [comment]
Rectifié !
