### ISSUE TITLE
Documentation sur le changement de fond de carte

### ISSUE THREAD

**Issue by Erzalt** [isogeo/doc-admin#75]
Ajout de la doc sur [le changement de fond de carte](https://github.com/isogeo/doc-admin/blob/master/fr/features/admin/group.md#fond-de-carte-des-applications). Il faut sûrement effectuer des captures d'écrans pour que cela soit plus clair.

**Comment by leodarengosse** [comment]
Petite erreur : "Dans le cas ou l'URL" --> où
Remplacer "il sera peut-être nécessaire " --> "il peut être nécessaire"

**Comment by Erzalt** [comment]
Modifs faites !
