### ISSUE TITLE
Rédiger la doc du ckan

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/doc-admin#77]

**Comment by leodarengosse** [comment]
J'ai mis à jour les prérequis (similaires à ceux du DCAT)

Je ne comprends toujours pas cette partie (Liste de champs "ressources" complétés). Peux-tu préciser et illustrer ce qui est complété et pourquoi ?

Les fréquences de màj ci-dessous n'existe pas dans Isogeo, pourquoi apparaissent-elles dans le tableau ?

| Temps réel          | À compléter manuellement |
| Irrégulier          | À compléter manuellement |
| Archives            | À compléter manuellement |

Dans les liens des services, de téléchargement des données et des cartes interactives 

J'ai rétiré les liens EFS comme pour le DCAT car ils ne fournissent pas de geojson en 4326 (surtout au canda ou la projection de l'arcgis server doit être la projection canadienne)

Ajouter une capture à Génération et suivi des jeux de données valides
J'ai retiré  `Mismatch between organization on CKAN and target organization` : Je ne sais pas
puisqu'on ne sait pas

**Comment by Mouzzi-C** [comment]
> Voici mes retours (j'ai déjà mis en QA certaines modifications)
> 
> J'ai mis à jour les prérequis (similaires à ceux du DCAT)
> 
> Je ne comprends toujours pas cette partie (Liste de champs "ressources" complétés). Peux-tu préciser et illustrer ce qui est complété et pourquoi ?

--> ça amrche, je vais ajouter ça.


> Les fréquences de màj ci-dessous n'existe pas dans Isogeo, pourquoi apparaissent-elles dans le tableau ?
> 
> | Temps réel | À compléter manuellement | | Irrégulier | À compléter manuellement | | Archives | À compléter manuellement |

--> ce sont des choix possibles sur DQ donc je les ai mis pour préciser que ça serait à faire manuellement si l'utilisateur souhaitait ajouter ces choix-là

**Comment by Mouzzi-C** [comment]
j'ai modifier la partie sur la liste de ressources et les fréquences de mise à jour. 

Il reste à ajouter les capture

**Comment by Mouzzi-C** [comment]
c'est fait, captures ajoutées

**Comment by leodarengosse** [comment]
Il manque la capture 

> Ajouter une capture à Génération et suivi des jeux de données valides

**Comment by Mouzzi-C** [comment]
c'est fait pour la capture. j'ai aussi renouvellé le jeton de l'api
