### ISSUE TITLE
Documentation sur l'import csv

### ISSUE THREAD

**Issue by Erzalt** [isogeo/doc-admin#78]
Ajout de la doc sur [l'import csv](https://github.com/isogeo/doc-admin/blob/master/fr/features/documentation/md_attributes.md#export-des-attributs-en-csv). Il faut sûrement effectuer des captures d'écrans pour que cela soit plus clair.

**Comment by leodarengosse** [comment]
J'ai traité mes retours directement dans la doc (cf. commit).
